"""
Job Role → Required Competency mapping for Indian Government Statistical Officials.
Maps designation to required competency levels.
"""

JOB_ROLE_REQUIREMENTS = {
    "Junior Statistical Officer": {
        "Statistical Data Collection": 3,
        "Data Entry & Validation": 3,
        "Basic Statistical Methods": 3,
        "Survey Design": 2,
        "MS Excel & Office Tools": 3,
        "Data Visualization": 2,
        "Government Data Standards": 2,
        "Written Communication": 2,
        "Teamwork & Collaboration": 2,
        "Ethical Data Handling": 2,
    },
    "Statistical Investigator": {
        "Statistical Data Collection": 4,
        "Survey Design": 3,
        "Sampling Techniques": 3,
        "Basic Statistical Methods": 4,
        "Advanced Statistical Analysis": 2,
        "Data Visualization": 3,
        "MS Excel & Office Tools": 3,
        "Database Management": 2,
        "Report Writing": 3,
        "Government Data Standards": 3,
        "Field Investigation Skills": 3,
        "Ethical Data Handling": 3,
    },
    "Senior Statistical Officer": {
        "Advanced Statistical Analysis": 4,
        "Sampling Techniques": 4,
        "Survey Design": 4,
        "Econometric Modelling": 3,
        "Data Visualization": 4,
        "Statistical Software (R/Python/SPSS)": 4,
        "Database Management": 3,
        "Report Writing": 4,
        "Project Management": 3,
        "Government Data Standards": 4,
        "Digital Governance Tools": 3,
        "Leadership & Mentoring": 3,
        "Ethical Data Handling": 4,
    },
    "Deputy Director (Statistics)": {
        "Advanced Statistical Analysis": 5,
        "Econometric Modelling": 4,
        "National Accounts & GDP Estimation": 4,
        "Statistical Software (R/Python/SPSS)": 4,
        "Big Data Analytics": 3,
        "Machine Learning Basics": 2,
        "Policy Analysis": 4,
        "Project Management": 4,
        "Leadership & Mentoring": 4,
        "Digital Governance Tools": 4,
        "Stakeholder Management": 4,
        "Government Data Standards": 5,
        "Written Communication": 4,
    },
    "Director (Statistics)": {
        "Advanced Statistical Analysis": 5,
        "Econometric Modelling": 5,
        "National Accounts & GDP Estimation": 5,
        "Big Data Analytics": 4,
        "Machine Learning Basics": 3,
        "Policy Analysis": 5,
        "Strategic Planning": 5,
        "Leadership & Mentoring": 5,
        "Stakeholder Management": 5,
        "Digital Governance Tools": 4,
        "Data Governance & Privacy": 4,
        "Government Data Standards": 5,
        "Change Management": 4,
    },
    "District Statistical Officer": {
        "Statistical Data Collection": 4,
        "Survey Design": 4,
        "Sampling Techniques": 3,
        "Basic Statistical Methods": 4,
        "Data Visualization": 3,
        "MS Excel & Office Tools": 4,
        "Database Management": 3,
        "Report Writing": 4,
        "Field Investigation Skills": 4,
        "Government Data Standards": 4,
        "Stakeholder Management": 3,
        "Digital Governance Tools": 3,
        "Ethical Data Handling": 4,
    },
    "Assistant Director (Census)": {
        "Statistical Data Collection": 5,
        "Survey Design": 4,
        "Sampling Techniques": 4,
        "Census Methodology": 4,
        "Database Management": 4,
        "GIS & Spatial Analysis": 3,
        "Project Management": 4,
        "Field Investigation Skills": 4,
        "Leadership & Mentoring": 3,
        "Government Data Standards": 4,
        "Digital Governance Tools": 3,
        "Ethical Data Handling": 4,
    },
}
